//
//  PlantModel.swift
//  Planta
//
//  Created by Oskar Hultman on 2022-11-09.
//

import Foundation


struct Plant: Codable, Identifiable {
    var id = UUID()
    var name: String
    var image: String
    var description: String
    var location: String
    
}

extension Plant {
    static let all: [Plant] = [Plant(name: "Monstera", image:"https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dw1af58434/images/large/521144-4017891310947.jpg?sh=1236&sfrm=jpg", description: "Mycket lättskött och populär planta med stora, blanka, gröna blad och långa luftrötter. Får dekorativa hål i bladen. Låt den torka lätt mellan vattningarna. Duscha bladen ofta.", location: "Inne"),
                               Plant(name: "StrandKastanj", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dwf73328e9/images/large/510929-Pachira%2017%20cm%207058782379947.jpg?sh=1236&sfrm=JPG", description: "Skulptural växt med en dekorativ, vacker stam och eleganta blad på långa bladstjälkar. Trivs på ljusa platser, undvik direkt solljus. Vattnas när jorden nästan har torkat ut. Duscha gärna bladen ofta.", location: "Inne"),
                               Plant(name: "Linspeperomia", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dwb0fec2e3/images/large/521073-Rotundifolia-10-5-cm-item-521073.jpg?sh=1236&sfrm=jpg", description: "Dekorativ bladväxt med små, ljusgröna blad på hängande grenar. Runt och tätt växtsätt. Lättodlad. Trivs i ljus och halvskugga, undvik direkt solljus. Vattnas när jorden har torkat ut.", location: "Inne"),
                               Plant(name: "Vinterbär", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dw7bbd1a07/images/large/510391-7058782364233.jpg?sh=1236&sfrm=jpg", description: "Frodig buske med vintergröna, glänsande blad och rosaröda blomknoppar hela vintern, ser ut som små bär. Trivs i sol-halvskugga i väldränerad mullrik jord. Frosttålig men ej härdig.", location: "Ute"),
                               Plant(name: "Novemberkaktus", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dw6fff7d67/images/large/520985-5708869180653.jpg?sh=1236&sfrm=jpg", description: "En lättskött och fin krukväxt, där äldre exemplar kan få ett mer hängande växtsätt. Blommar med vackra, dubbla blommor. Trivs bäst i ljusa miljöer med jämn temperatur, låt torka upp lätt mellan vattningarna.", location: "Ute"),
                               Plant(name: "Porslinsblomma på båge", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dw994981d2/images/large/514858-5708869292868.jpg?sh=1236&sfrm=jpg", description: "Vacker och populär planta på en båge med tjocka, mörkgröna, blanka blad. Porslinsblomman är en tålig växt som med god tillgång till ljus får små vita blommor. Låt den torka lätt mellan vattningarna.", location: "Inne"),
                               Plant(name: "Kaktuseuforbia", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dw447e8d3e/images/large/510912-70587823796401.jpg?sh=1236&sfrm=png", description: "Lättskött, och trendig suckulent med upprätt karaktäristiskt växtsätt. Torktålig och kravlös. Trivs i ljust, gärna soligt läge. Vattnas då jorden helt torkat upp.", location: "Inne"),
                               Plant(name: "Elefantöra", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dw62678edb/images/large/514923-5708869335916.jpg?sh=1236&sfrm=jpg", description: "En återfödd 70-talsklassiker med karakteristiska runda blad på långa stjälkar. Mycket dekorativ och lätt att sköta. Trivs i sol-halvskugga. Vattna när jorden lätt torkat upp.", location: "Inne"),
                               Plant(name: "Aloe Vera", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dwe3edd4f0/images/large/530479-Aloe%20vera%208.5cm.jpg?sh=1236&sfrm=png", description: "Lättskött suckulent med tjocka gröna blad. En av världens äldsta läkeväxkter. Trivs på soliga platser. Låt den torka ut mellan varje vattning.", location: "Inne"),
                               Plant(name: "Citronfikus", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dwf0556d46/images/large/534979-Ficus%20microcarpa%20S-shape%2033%20cm%20item%20534979.jpg?sh=1236&sfrm=jpg", description: "En vacker stor planta med blanka, små gröna blad. Ett lättskött alternativ till en bonsai. Trivs i ljusa förhållanden. Låt den torka lätt mellan vattningarna. Duscha den gärna på bladen emellanåt.", location: "Inne"),
                               Plant(name: "Pinnlilja", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dwebd2e7fe/images/large/517336-Aloe%20Vera%205.5cm%20-%202.jpg?sh=1236&sfrm=png", description: "Lättskött suckulent med cylinderformade tjocka blad med mörkgrön färg. Låt den torka ut mellan varje vattning. Trivs i halvskugga.", location: "Inne"),
                               Plant(name: "Olivträd", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dwe245f26e/images/large/521162-Olea%20europaea%20stem%2019%20cm-7058782377363%20a.jpg?sh=1236&sfrm=jpg", description: "Olivträd för den rätta medelhavskänslan! Får vackra, läderartade blad i silvergrått. Trivs i sol-halvskugga i väldränerad jord, gärna utomhus sommartid. Låt torka upp mellan rikliga vattningar.", location: "Ute"),
                               Plant(name: "Marmorblad", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dwe3517e94/images/large/517407-Calathea%20Lancifolia%2019cm.jpg?sh=1236&sfrm=jpg", description: "Fin och spännande växt med kontrastrika blad med grönt mönster och lila undersida på bladen. Trivs i ljus och halvskugga, undvik direkt solljus. Håll jorden lätt fuktig. Gillar att bli duschad på bladen.", location: "Inne"),
                               Plant(name: "Murgröna", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dwc7703d79/images/large/514814-57088692232821.jpg?sh=1236&sfrm=jpg", description: "Populär växt med femflikiga, mörkgröna blad. Trivs i halvskugga, undvik direkt solljus. Vattnas när jorden fortfarande är något fuktig. Kan gärna duschas.", location: "Inne"),
                               Plant(name: "Julros", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dwa28096dd/images/large/7058782399389.jpg?sh=1236&sfrm=jpg", description: "En välkänd julblomma med stora och vackra kronblad i fin kontrast till det frodiga bladverket. Julstjärnan trivs i ljus och varm miljö. Undvik drag och kyla. Låt torka upp lätt mellan vattningarna.", location: "Inne"),
                               Plant(name: "Brudorkidé", image: "https://www.plantagen.se/dw/image/v2/BCMR_PRD/on/demandware.static/-/Sites-inriver-catalog/default/dwcab43397/images/large/510878-7058782377547.jpg?sh=1236&sfrm=jpg", description: "Orkidé som drar blicken till sig med blå, hållbara blommor på höga, eleganta stjälkar. Lång blomningstid. En lättskött växt som ger ett elegant uttryck. Sorten är artificiellt blåfärgad.", location: "Inne")]
}
